### ISSUE TITLE
API for applyKernal function?

### ISSUE THREAD

**Issue by DavidBrainard** [gkaguirrelab/temporalFittingEngine#12]
Q about interface to applyKernal function.  Currently this takes a timebase, a response and a kernal.  Would it be more flexible if we eliminated the timebase argument and passed two structures, one for response and one for kernal, that have timebase and values fields, and return a structure that has a timebase and value field?  The deeper question is are we always going to pass around temporal functions as structures with timebase and values fields, or are we sometimes going to pass around the pieces.  The other place this applies is to the plot method.

**Comment by spitschan** [comment]
I believe that the current specification of a packet has:

```
packet.response.values
packet.response.timebase
packet.stimulus.values
packet.stimulus.timebase
packet.kernel.values
packet.kernel.timebase
```

(And meta data.)

I think it might be nice not to enforce same time bases for each of these three types of 'data'. It would make things a little more general purpose, I think. The `isPacket` function should check, though, that the dimensions of the timebase-values pairs are the same. I think it's doing that already.

**Comment by DavidBrainard** [comment]
I think we decided in our meeting yesterday that the timebases for different elements of the packet could in fact differ, for good reasons.

**Comment by spitschan** [comment]
Yes, good. I wasn't sure if that had been decided definitively.

**Comment by gkaguirre** [comment]
David's description is my understanding as well.

One thing we should decide upon, and thus instantiate in isPacket:

```
 Should packet.stimulus.timebase be a one-dimension row vector, just like the other timebase entries?
```

The only reason we might entertain this not being the case is because packet.stimulus.values can be a matrix. However, I think it is a good requirement at this stage that every row vector contained in stimulus.values is referable to the same timebase.

If no objections, I can instantiate this requirement in isPacket.

**Comment by DavidBrainard** [comment]
I would vote for common stimulus timebase.
