### ISSUE TITLE
toolboxRegistry file

### ISSUE THREAD

**Issue by DavidBrainard** [gkaguirrelab/temporalFittingEngine#15]
I updated the toolboxRegistry JSON file to include BrainardLabToolbox and one subfolder (Psychometric) of the Psychtoolbox.  These are needed by the QCM.

I also removed the JSON file and the Matlab file that creates it from the Configuration directory.  a) It is as easy to edit the JSON as it is to edit the Matlab, and removing the Matlab cuts out the middle man.  b) I don't like having two copies of things -- I think the master should just live in the toolboxRegistry and we can edit that when we want to change it.

**Comment by gkaguirre** [comment]
Thanks for opening this. Perhaps this topic is more TbTb than tfe...

My preference is for the temporal fitting engine to not require additional toolboxes unless the model subclass requires it. 

I don't, however, see a way to achieve this kind of granular control in an automated way using TbTb. The approach I had considered was to have models declare in some fashion their dependencies, and then place the onus upon the analysis code to make these available.

**Comment by DavidBrainard** [comment]
I think there are some options  It may be we should wait until we have at least one working project before we try to resolve, as getting some experience with ways to deploy things may clarify the best solution.
