### ISSUE TITLE
delete bockDev branch?

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/temporalFittingEngine#21]
@bock42 : Looks to me like this branch is way behind the times. Perhaps delete?

**Comment by gkaguirre** [comment]
Yoo-hoo, @bock42 !!

**Comment by bock42** [comment]
I will compare this branch to `master` today

**Comment by bock42** [comment]
`bockDev` is now up-to-date with `master`.  I have opened a pull request, there are no conflicts with the `master` branch

**Comment by bock42** [comment]
It is also quite easy to update a branch with `master`.  The command line usage for `bockDev` branch:

`git checkout bockDev`
`git fetch origin`
`git merge origin/master`

If there are any conflicts, you can resolve them locally before opening a pull request.
