### ISSUE TITLE
resampleTimebase edits and unit test

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/temporalFittingEngine#26]
The parent tfe class includes the method resampleTimebase. Andrew had written a padResample function as part of the BCDM model. The resampleTimebase method requires some validation tests,and we should determine if the padResample function has components that we should integrate into the primary method.

**Comment by gkaguirre** [comment]
Andrew -- Step 1 would be to create the file (and directory):
  temporalFittingEngine/temporalFittingEngine/@tfe/validationsTFE/validateResampleTimebase.m

This code would instantiate a temporal fitting object, create a number of different testStruct variables with timebase and value entries, and then submit these to the resampleTimebase method. The output of the method could then be checked against desired output.

For example, in the case of a vector with sparse entries (e.g., a vector of zeros with an occasional 1), what is the desired behavior for down-sampling that vector to a timebase with a 10 times reduction in deltaT? My view is that the sparse event would be represented in the output vector as having a value of 0.1 in the array position corresponding to the down sample, but this is what we would need to consider.

In this process, you may discover that the resampleTimebase method requires updating or changing. I know that you have investigated some of these properties previously.

**Comment by bock42** [comment]
I will create the desired directory and function(s).  Briefly, I no longer use the `padResample` function, and also no longer use `resample`.  The `resample` function has some odd behaviors when the first/last values are non-zero, an issue that is addressed by `padResample`.  However, I have further found that the anti-aliasing filter found in the `resample` function has some odd behaviors for vectors that are not sinusoidal - such as a vector of sparse entries described above - as it attempts to preserve the frequencies found in the original vector.

I currently use `downsample`, which thus far I have found to produce the same result as using `interp1` with linear interpolation, provided a constant deltaT.  I will continue my search for a better solution, though, and will keep you updated if I find the resampleTimebase method requires updating.

**Comment by gkaguirre** [comment]
The place to start is with the testing code.

I have created the file:
  temporalFittingEngine/temporalFittingEngine/validationsTFE/resampleTimebaseValidate.m

This routine contains a very simple example test upon the resample routine. You can expand upon this. This exercise will lead us to establish what we want the resampling behavior to be in different cases.
