### ISSUE TITLE
Don't trust applyKernel

### ISSUE THREAD

**Issue by DavidBrainard** [gkaguirrelab/temporalFittingEngine#31]
I wrote a quick test of applyKernel on the ConvValidation branch and it does not appear to work right.  I will be working to fix this up, but just be aware that we should currently be suspect of any result which relies on applyKernel.

**Comment by DavidBrainard** [comment]
A big problem is this line in applyKernel: zeroAlignedKernel = kernelStruct.values-kernelStruct.values(1);

I do not see why this is a good idea.  Certainly it takes a delta function kernel (which was my first test case and makes it something very different).

**Comment by bock42** [comment]
I recommend NOT using 'same' when using `conv`, as it gives you the central part of the convolution.  Typically you want the first part of the output, up to the length of the input vector.  Thus, one solution is to use 'full' <default> when using `conv`, and then remove the extra values at the end.  

Alternatively, you can use `filter`.  This is how I do my convolution using an HRF kernel.

**Comment by gkaguirre** [comment]
Agree that initial zero should not be part of applyKernel. 

The calling functions are responsible for having a kernel that is properly constructed.

**Comment by spitschan** [comment]
Is this fixed now?

**Comment by gkaguirre** [comment]
@DavidBrainard : Can we consider this issue now closed?

**Comment by DavidBrainard** [comment]
Yes, closed I think.
