### ISSUE TITLE
tfe fails when passed all nans

### ISSUE THREAD

**Issue by harrison-mcadams** [gkaguirrelab/temporalFittingEngine#57]
I was attempting to use the IAMP model to determine the amplitude of individual trials of pupil constriction. The routine fails when the packet passed to the tfe contains all NaN values. If the response contains only some NaNs, the routine functions appropriately, but if the response contains only NaNs, the routine breaks and the following error message is displayed: 

Error using tfe/fitError (line 51)
the model has returned an undefined error measurement

Error in tfe/fitResponse>@(modelParamsVec)obj.fitError(modelParamsVec,thePacket) (line 72)
       paramsFitVec = fmincon(@(modelParamsVec)obj.fitError(modelParamsVec, ...

Error in fmincon (line 535)
     initVals.f = feval(funfcn{3},X,varargin{:});

Error in tfe/fitResponse (line 72)
       paramsFitVec = fmincon(@(modelParamsVec)obj.fitError(modelParamsVec, ...

Error in fitIAMPToSubjectAverageResponses_byTrial (line 119)
               [paramsFit,fVal,modelResponseStruct] =
               temporalFit.fitResponse(packetCellArray{trial}, 'defaultParamsInfo',
               defaultParamsInfo,'paramLockMatrix',paramLockMatrix);

Caused by:
   Failure in initial objective function evaluation. FMINCON cannot continue.

**Comment by gkaguirre** [comment]
Upon further reflection, I think it is not unreasonable to have the routine crash if it is receiving data that consists only of NaNs. I can think of more graceful exits, but this should be a relatively rare error state.
