### ISSUE TITLE
toolbox on the narrowest grounds possible

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/temporalFittingEngine#63]
I'd like to remove BLTB and Psychtoolbox from the config for the tfe. The principle at work is that a toolbox should not place on your path functions that are not strictly necessary for the operation of said toolbox.

Currently, QCM is the only model that would break under this change. If QCM needs BLTB / Psychtoolbox, then QCM could move out of the tfe and be promoted to the status of a "project". Alternatively, the specific matlab central / GitHub repos needed for QCM operation could be identified and the added individually to the tfe config.

**Comment by render-toolbox** [comment]
OK to take these out.  Next time I'm back in QCM I will figure out what is needed.  TbTb allows specification of specific subfolders only to go onto the path; I expect what I'll want to do is figure out just which subfolders I need and put those back on.  This results in the whole PTB or BLTB being on the computer, but only the needed folders being on the path.

Thinking generally about the right granularity for toolboxes is a good idea.  I don't think it is as fine as one function per toolbox, but in the era of TbTb it is probably finer than PTB and BLTB.

**Comment by gkaguirre** [comment]
These toolboxes have been removed and QCM removed from the validation set. We'll stand this back up when needed.
